/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <pwm.h>
#include <stdint.h>
#include "stm32f103xx.h"
#include "gpio.h"
#include "spi.h"
#include <string.h>
#include "adc.h"
#include "dma.h"
#include "nvic.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint8_t adcChannelArray[1] = {1};
volatile uint8_t dmaData = 0;
SPI_Handle_t spi;

int main(void)
{

	GPIO_Handle_t sckPin, mosiPin, nssPin;

	char data[] = "HelloWorld";

	spi.pSPIX = SPI1;
	spi.pSPIConfig.SPI_DeviceMode = SPI_MASTER;
	spi.pSPIConfig.SPI_DFF = SPI_DFF_8;
	spi.pSPIConfig.SPI_BusConfig = SPI_BUS_FULL_DUPLEX;
	spi.pSPIConfig.SPI_BaudRate = SPI_BAUD_PCLK_DIV2;
	spi.pSPIConfig.SPI_CPOL = SPI_CPOL_LO;
	spi.pSPIConfig.SPI_CPHA = SPI_CPHA_LO;
	spi.pSPIConfig.SPI_SSM = SPI_SSM_DI;

	sckPin.pGPIOX = GPIOA;
	sckPin.GPIO_PinConfig.pinMode = AF_PUSH_PULL_50MHZ;
	sckPin.GPIO_PinConfig.pinNumber = 5;

	mosiPin.pGPIOX = GPIOA;
	mosiPin.GPIO_PinConfig.pinMode = AF_PUSH_PULL_50MHZ;
	mosiPin.GPIO_PinConfig.pinNumber = 7;

	nssPin.pGPIOX = GPIOA;
	nssPin.GPIO_PinConfig.pinMode = AF_PUSH_PULL_50MHZ;
	nssPin.GPIO_PinConfig.pinNumber = 4;

	GPIO_ClockControl(GPIOA,ENABLE);
	GPIO_Init(&sckPin);
	GPIO_Init(&mosiPin);
	GPIO_Init(&nssPin);

	SPI_ClockControl(SPI1,ENABLE);

	SPI_Init(&spi);

	while(1){
		while ( SPI_SendDataIT(&spi,(uint8_t*)&data,strlen(data)) == SPI_BUSY_IN_TX);
	}
}

void SPI1_IRQHandler(){
	SPI_IRQHandling(&spi);
}

void SPI_ApplicationEventCallback(SPI_Handle_t *pSPIHandle,uint8_t AppEv){
	if(AppEv==SPI_EVENT_TX_CMPLT){
		while(pSPIHandle->pSPIX->SR.BSY);
		pSPIHandle->pSPIX->CR1 &= (~1<<SPI_SPE_POS);
	}
}
